### ISSUE TITLE
Feature Request: Account Manager Per Company

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#100]
Right now I'm updating the account managers for each site.  It is a long process.  Can we tie all sites of one company to one account manager.  Then maybe we can make this available to the account managers to update as well.

**Comment by pinkynrg** [comment]
the structural change is not small. If it is something really needed we could do it in the future, but right now we have less then 100 sites so I don't feel it is really important to make the process of associating account managers to companies faster.
