### ISSUE TITLE
Phone Extension

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#105]
Some extensions are longer than 4 digits I believe

![image](https://cloud.githubusercontent.com/assets/17487070/15287613/bf191d2e-1b29-11e6-985d-3fcd3b00a58a.png)

**Comment by pinkynrg** [comment]
see also issue #131. Possibility I will solve them both within one commit.

**Comment by pinkynrg** [comment]
Fixed. Now can make it as long as 6 chars. Closing.
