### ISSUE TITLE
Grammar. Password change page

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#108]
![2016-05-17 03_31_29](https://cloud.githubusercontent.com/assets/17487070/15325704/e1b0d088-1c10-11e6-8bea-a5b6747177e6.png)

"Before you start, please provide the following information."

"Please fill out each tab 
OR 
Use the same information for all of your contacts by checking 'Use info for all'

**Comment by pinkynrg** [comment]
fixed.
