### ISSUE TITLE
Notification: Customer Creator gets email when changing Assignee

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#112]
![image](https://cloud.githubusercontent.com/assets/17487070/15357779/69987db0-1cc6-11e6-959a-45e2e1cf4bd7.png)

Plus he gets it twice since he is also the contact.  I don't think customers should get an email unless we make a post, so we don't spam them.  We can talk about that more, but in this case they shouldn't,

**Comment by e80tom** [comment]
![image](https://cloud.githubusercontent.com/assets/17487070/15358534/8452ebaa-1cca-11e6-9403-cae6ac006581.png)

Also when added a link to another ticket, and the body of the message doesn't say anything.

**Comment by pinkynrg** [comment]
For ticket update I will send an email only to the assignee then.

**Comment by pinkynrg** [comment]
I also checked the second issue and it looks to be no longer an issue. It was probably an issue when it was work in progress. 

> Question: now I'm not keeping in the ticket history changes to ticket links and tags. Unfortunately I have no time to make it work now, but in the future maybe. Please write a new ticket in case you think it is a good idea to have it.

Thanks
