### ISSUE TITLE
Service form has a duplicate entry for remote dev hours

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#122]
The remote dev end date hours input has a duplicate on the right side which throws out of place the date fields for the on-site portion.
![rem deve hours](https://cloud.githubusercontent.com/assets/16998313/15401995/97c716fa-1db7-11e6-9882-891289d43780.PNG)

**Comment by pinkynrg** [comment]
fixed thanks. Have no idea how that field got duplicated. Used to be fine. Thanks
