### ISSUE TITLE
Got error when trying to view service request

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#123]
Created a service request successfully but when I tried to view the request I got this error.

ErrorException in 6679404fc590198c5773662e08c22c03 line 23:

Trying to get property of non-object (View: /home/forge/default/resources/views/services/show.blade.php)
1. in 6679404fc590198c5773662e08c22c03 line 23
   2.at CompilerEngine->handleViewException(object(ErrorException), '1') in PhpEngine.php line 44
   3.at PhpEngine->evaluatePath('/home/forge/default/storage/framework/views/6679404fc590198c5773662e08c22c03', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'menu_actions' => array(array('label' => 'Generate Service PDF', 'link' => 'https://convergence.elettric80inc.com/services/generate/pdf/169', 'icon' => '<i class='fa fa-plus'></i>', 'show' => true)), 'title' => 'Service', 'service' => object(Service))) in CompilerEngine.php line 58
   4.at CompilerEngine->get('/home/forge/default/resources/views/services/show.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'menu_actions' => array(array('label' => 'Generate Service PDF', 'link' => 'https://convergence.elettric80inc.com/services/generate/pdf/169', 'icon' => '<i class='fa fa-plus'></i>', 'show' => true)), 'title' => 'Service', 'service' => object(Service))) in View.php line 147
   5.at View->getContents() in View.php line 118
   6.at View->renderContents() in View.php line 83
   7.at View->render() in Response.php line 51
   8.at Response->setContent(object(View)) in Response.php line 200
   9.at Response->__construct(object(View)) in Router.php line 1229
   10.at Router->prepareResponse(object(Request), object(View)) in ControllerDispatcher.php line 113
   11.at ControllerDispatcher->Illuminate\Routing{closure}(object(Request))
   12.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
   13.at Pipeline->Illuminate\Pipeline{closure}(object(Request))
   14.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
   15.at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 114
   16.at ControllerDispatcher->callWithinStack(object(ServicesController), object(Route), object(Request), 'show') in ControllerDispatcher.php line 69
   17.at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\ServicesController', 'show') in Route.php line 203
   18.at Route->runWithCustomDispatcher(object(Request)) in Route.php line 134
   19.at Route->run(object(Request)) in Router.php line 708
   20.at Router->Illuminate\Routing{closure}(object(Request))
   21.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
   22.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in LogRequests.php line 31
   23.at LogRequests->handle(object(Request), object(Closure))
   24.at call_user_func_array(array(object(LogRequests), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   25.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in Authenticate.php line 47
   26.at Authenticate->handle(object(Request), object(Closure))
   27.at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   28.at Pipeline->Illuminate\Pipeline{closure}(object(Request))
   29.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
   30.at Pipeline->then(object(Closure)) in Router.php line 710
   31.at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 675
   32.at Router->dispatchToRoute(object(Request)) in Router.php line 635
   33.at Router->dispatch(object(Request)) in Kernel.php line 236
   34.at Kernel->Illuminate\Foundation\Http{closure}(object(Request))
   35.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
   36.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in Debugbar.php line 49
   37.at Debugbar->handle(object(Request), object(Closure))
   38.at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   39.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in VerifyCsrfToken.php line 50
   40.at VerifyCsrfToken->handle(object(Request), object(Closure)) in VerifyCsrfToken.php line 17
   41.at VerifyCsrfToken->handle(object(Request), object(Closure))
   42.at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   43.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in ShareErrorsFromSession.php line 49
   44.at ShareErrorsFromSession->handle(object(Request), object(Closure))
   45.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   46.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in StartSession.php line 62
   47.at StartSession->handle(object(Request), object(Closure)) in StartSessionExtended.php line 20
   48.at StartSessionExtended->handle(object(Request), object(Closure))
   49.at call_user_func_array(array(object(StartSessionExtended), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   50.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
   51.at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
   52.at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   53.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in EncryptCookies.php line 59
   54.at EncryptCookies->handle(object(Request), object(Closure))
   55.at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   56.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
   57.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
   58.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   59.at Pipeline->Illuminate\Pipeline{closure}(object(Request))
   60.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
   61.at Pipeline->then(object(Closure)) in Kernel.php line 122
   62.at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
   63.at Kernel->handle(object(Request)) in index.php line 53

1/2

ErrorException in 6679404fc590198c5773662e08c22c03 line 23:

Trying to get property of non-object
1. in 6679404fc590198c5773662e08c22c03 line 23
   2.at HandleExceptions->handleError('8', 'Trying to get property of non-object', '/home/forge/default/storage/framework/views/6679404fc590198c5773662e08c22c03', '23', array('__path' => '/home/forge/default/storage/framework/views/6679404fc590198c5773662e08c22c03', '__data' => array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'menu_actions' => array(array('label' => 'Generate Service PDF', 'link' => 'https://convergence.elettric80inc.com/services/generate/pdf/169', 'icon' => '<i class='fa fa-plus'></i>', 'show' => true)), 'title' => 'Service', 'service' => object(Service)), 'obLevel' => '1', '__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'menu_actions' => array(array('label' => 'Generate Service PDF', 'link' => 'https://convergence.elettric80inc.com/services/generate/pdf/169', 'icon' => '<i class='fa fa-plus'></i>', 'show' => true)), 'title' => 'Service', 'service' => object(Service))) in 6679404fc590198c5773662e08c22c03 line 23
   3.at include('/home/forge/default/storage/framework/views/6679404fc590198c5773662e08c22c03') in PhpEngine.php line 42
   4.at PhpEngine->evaluatePath('/home/forge/default/storage/framework/views/6679404fc590198c5773662e08c22c03', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'menu_actions' => array(array('label' => 'Generate Service PDF', 'link' => 'https://convergence.elettric80inc.com/services/generate/pdf/169', 'icon' => '<i class='fa fa-plus'></i>', 'show' => true)), 'title' => 'Service', 'service' => object(Service))) in CompilerEngine.php line 58
   5.at CompilerEngine->get('/home/forge/default/resources/views/services/show.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'menu_actions' => array(array('label' => 'Generate Service PDF', 'link' => 'https://convergence.elettric80inc.com/services/generate/pdf/169', 'icon' => '<i class='fa fa-plus'></i>', 'show' => true)), 'title' => 'Service', 'service' => object(Service))) in View.php line 147
   6.at View->getContents() in View.php line 118
   7.at View->renderContents() in View.php line 83
   8.at View->render() in Response.php line 51
   9.at Response->setContent(object(View)) in Response.php line 200
   10.at Response->__construct(object(View)) in Router.php line 1229
   11.at Router->prepareResponse(object(Request), object(View)) in ControllerDispatcher.php line 113
   12.at ControllerDispatcher->Illuminate\Routing{closure}(object(Request))
   13.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
   14.at Pipeline->Illuminate\Pipeline{closure}(object(Request))
   15.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
   16.at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 114
   17.at ControllerDispatcher->callWithinStack(object(ServicesController), object(Route), object(Request), 'show') in ControllerDispatcher.php line 69
   18.at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\ServicesController', 'show') in Route.php line 203
   19.at Route->runWithCustomDispatcher(object(Request)) in Route.php line 134
   20.at Route->run(object(Request)) in Router.php line 708
   21.at Router->Illuminate\Routing{closure}(object(Request))
   22.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
   23.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in LogRequests.php line 31
   24.at LogRequests->handle(object(Request), object(Closure))
   25.at call_user_func_array(array(object(LogRequests), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   26.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in Authenticate.php line 47
   27.at Authenticate->handle(object(Request), object(Closure))
   28.at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   29.at Pipeline->Illuminate\Pipeline{closure}(object(Request))
   30.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
   31.at Pipeline->then(object(Closure)) in Router.php line 710
   32.at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 675
   33.at Router->dispatchToRoute(object(Request)) in Router.php line 635
   34.at Router->dispatch(object(Request)) in Kernel.php line 236
   35.at Kernel->Illuminate\Foundation\Http{closure}(object(Request))
   36.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
   37.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in Debugbar.php line 49
   38.at Debugbar->handle(object(Request), object(Closure))
   39.at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   40.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in VerifyCsrfToken.php line 50
   41.at VerifyCsrfToken->handle(object(Request), object(Closure)) in VerifyCsrfToken.php line 17
   42.at VerifyCsrfToken->handle(object(Request), object(Closure))
   43.at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   44.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in ShareErrorsFromSession.php line 49
   45.at ShareErrorsFromSession->handle(object(Request), object(Closure))
   46.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   47.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in StartSession.php line 62
   48.at StartSession->handle(object(Request), object(Closure)) in StartSessionExtended.php line 20
   49.at StartSessionExtended->handle(object(Request), object(Closure))
   50.at call_user_func_array(array(object(StartSessionExtended), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   51.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
   52.at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
   53.at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   54.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in EncryptCookies.php line 59
   55.at EncryptCookies->handle(object(Request), object(Closure))
   56.at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   57.at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
   58.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
   59.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
   60.at Pipeline->Illuminate\Pipeline{closure}(object(Request))
   61.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
   62.at Pipeline->then(object(Closure)) in Kernel.php line 122
   63.at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
   64.at Kernel->handle(object(Request)) in index.php line 53

**Comment by pinkynrg** [comment]
fixed. thanks
