### ISSUE TITLE
Email notification for customer

### ISSUE THREAD

**Issue by e80sam** [pinkynrg/convergence2.0#126]
Attach links to documents along with post.  Currently images are not showing up when emails are sent to customer.  Email shows the post information  but no record of an attachment.  
![2016-05-19 15_05_35](https://cloud.githubusercontent.com/assets/18336458/15408028/b8289cea-1dd3-11e6-93ea-43d749fab3b6.png)
![2016-05-19 15_05_26](https://cloud.githubusercontent.com/assets/18336458/15408029/bc4510b0-1dd3-11e6-8b41-b250c440d1ba.png)

**Comment by pinkynrg** [comment]
done. please test.
