### ISSUE TITLE
View permission group and company on User page

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#128]
![image](https://cloud.githubusercontent.com/assets/17487070/15469025/39ee8ee8-20ad-11e6-9f71-930cd5cbfff8.png)

I'd like to see the permissions groups. I'd like to see this for E80 employees mostly, since it may be the same for customers.
I don't know if we need to see hashed password, but maybe there is a reason.

**Comment by pinkynrg** [comment]
permissions group are associated to contacts. I can insert the permission group in there.

**Comment by pinkynrg** [comment]
either companies are not a 1 to 1 relation with user. You wanna look for this attribute in the contacts page. I inserted the permissions group there as well now. Check next push. closing.

**Comment by e80tom** [comment]
I'd like to see company rather than hashed password.

**Comment by e80tom** [comment]
so i can see which users exist for a certain company
