### ISSUE TITLE
Set Contact Division

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#133]
I set the division for a new contact I created, but still the active tickets were not shown.

![2016-05-23 07_17_48](https://cloud.githubusercontent.com/assets/17487070/15470527/cd66900e-20b6-11e6-9056-9c40586d9d6e.png)

Then I tried it from the new contact's account, and got "group id field is required' error.

![2016-05-23 07_19_15](https://cloud.githubusercontent.com/assets/17487070/15470554/e782200c-20b6-11e6-9812-a59e0aaa96eb.png)

**Comment by pinkynrg** [comment]
fixed.
