### ISSUE TITLE
Remove Waiting for Parts from Active

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#135]
![image](https://cloud.githubusercontent.com/assets/17487070/15475873/cb2dd4ee-20d1-11e6-9bca-2b3a2a5e9ee7.png)

WFP

**Comment by e80tom** [comment]
then maybe they should require a public post when changing to this status just like WCF.

**Comment by pinkynrg** [comment]
fixed. wait next push on #convergence channel.
