### ISSUE TITLE
customer user permission group

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#143]
I created a new user that seems to be set to use the customer host by default and this user does not seem to be able to create ticket requests or edit tickets.
Then I tried to change the users permission but this field is not enabled to be edited.

![permission](https://cloud.githubusercontent.com/assets/16998313/15575687/c5e9ba44-2319-11e6-85b3-cbf864969c2e.PNG)

**Comment by pinkynrg** [comment]
this is wanted for now until you guys are really familiar with the environment. I'm giving out permission little by little and for now nobody but me is allowed to change permission groups.
