### ISSUE TITLE
Customer site does not seem to have filters

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#144]
The customer site does not seem to have the filters enabled for the customer to check only LGV issues or only the issues in progress.

We need to think about the needs of the customer from the site and develop the tools that will make the site good for them. For example, as a customer one thing you want to be able to do is quickly check your tickets open (tickets in progress and tickets waiting for feedback). We can probably achieve this with the filters but it may be useful to have a couple of quick links similar to the internal dashboard but for the customer such as "my tickets waiting for feedback" and "my open tickets".

**Comment by pinkynrg** [comment]
What filter do you think we should for the customer? They don't need to be the same filters we have, I can create custom one only for them, or also new ones for the both of us.

**Comment by EffEss** [comment]
At the very least, Division and Status filters

**Comment by pinkynrg** [comment]
ok filters for division and status added. Closing.
