### ISSUE TITLE
Submitting Ticket

### ISSUE THREAD

**Issue by e80sam** [pinkynrg/convergence2.0#147]
I encountered error submitting RCA for ticket 4581.  I set the ticket to solved and clicked submit.  I was brought to a page saying "oops something went wrong".   No errors were generated by the error page.   After refreshing the page, the ticket was set to solved and an RCA was posted.   Screenshots below are from ticket 4581 after refresh.  

![screen shot 2016-05-29 at 10 48 26 am](https://cloud.githubusercontent.com/assets/18336458/15634495/1b4edba4-258b-11e6-883b-c7286d1179ee.png)
![screen shot 2016-05-29 at 10 48 33 am](https://cloud.githubusercontent.com/assets/18336458/15634497/2335780a-258b-11e6-84c3-4b88025e0958.png)

**Comment by pinkynrg** [comment]
solved. see Slack @ #convergence channel. Closing.
