### ISSUE TITLE
Basic Users should be allowed to create and edit tickets

### ISSUE THREAD

**Issue by nielsen-g** [pinkynrg/convergence2.0#153]
At this time Basic E80 Users cannot create or edit tickets. Most notably this causes confusion when a customer creates a ticket request. It looks like a ticket, and shows up just like all the others, but a basic user cannot finalize the ticket so they can begin updating it.

In general I feel that any action not reserved for managers should be preform able by a Basic E80 User. It makes more sense to train our own people to use all the features of Convergence than to block key features to the majority of users which degrades our ability to assist our customers quickly and effectively.

**Comment by e80tom** [comment]
I agree we can open it up, so at least Raj, JJ etc can create the ticket from the request. In this case JJ couldn't do it, and Raj couldn't.  We can monitor if they do something incorrectly.

**Comment by pinkynrg** [comment]
i don't feel like evert employee can change tickets. I feel more like ad additional permission group should be created for them? Like basic-technician...

Who's JJ? the polish guy? what does he do in E80? I understand Raj may need to moderate a ticket request but I don't know about JJ.

**Comment by e80tom** [comment]
JJ is the a key account manager who was a top guy on the e80 reliability team. He works with a lot of the electromechanical guys at all the sites. Especially Niagara.

Someone could have created the ticket for him that, but I trust him to do it. He's also the one who requested to be notified for all Niagara issues.

Raj definitely should be able to.

**Comment by pinkynrg** [comment]
I will create a basic-technician i give the the possibility to moderate tickets. Closing.
