### ISSUE TITLE
Tag data does not clear on tab

### ISSUE THREAD

**Issue by nielsen-g** [pinkynrg/convergence2.0#154]
When you write a tag in a ticket and you select one from the drop down or by hitting tab the text that you typed remains 
![2016-06-03 14_52_17](https://cloud.githubusercontent.com/assets/19736537/15791113/15f233f4-299b-11e6-86ca-455457104152.png)

**Comment by pinkynrg** [comment]
Duplicated. Closing. See ticket #109.
