### ISSUE TITLE
Customer Title & Department

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#158]
Since we don't have a great selection in the drop down list, maybe we can let the customer edit those fields, so we have a more accurate description of what they do.  We can edit it later if we want.

**Comment by e80tom** [comment]
I would like to do this soon if possible now that everyone is logging in for the first time.

**Comment by pinkynrg** [comment]
No i don't like to have the customer select its title since I also think we can get from the internet a pretty decent list of titles that we could use.

**Comment by pinkynrg** [comment]
Let's try to find a good solid list online with max 100 entries so we can update that horrible list as soon as possible.

**Comment by pinkynrg** [comment]
done. wait next commit and check on devel.
