### ISSUE TITLE
Mobile Filters don't scroll

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#165]
The drop-down list doesn't scroll.  Also we can't see when something is selected in the mobile view when the text is long.

![screenshot_20160608-164706](https://cloud.githubusercontent.com/assets/17487070/15913321/d6fd00a4-2d9e-11e6-9917-4235d2c861bd.png)

**Comment by pinkynrg** [comment]
of course you can scroll please double check. For the company not visible checks when company list is too long it make sense, I will fix it, in the mean time it would also make sense to make this list of company names shorter:

```
id; name
129; Sofidel - Haines City (Formerly Cellynne)
163; Ardagh Glass - Dunkirk (Saint-Gobain)
164; Ardagh Glass - Lincoln (Saint-Gobain)
165; Ardagh Glass - Pevely (Saint-Gobain)
197; Georgia Pacific - Northwest Service Center (Disabled)

```

**Comment by pinkynrg** [comment]
do we even need company id = 197?

**Comment by e80tom** [comment]
We don't need them, buy they may have tickets.

I tried scrolling again with no success. Using chrome on Android.

**Comment by pinkynrg** [comment]
fixed. when on mobile now it activates the native select/multiselect of the mobile browser. It is now not possible to search before selecting when on mobile device. So when it comes to select/multiselect out of long lists of options (such as selecting the title from the new title list, +500 options), it is better to use convergence on a regular screen.
