### ISSUE TITLE
Can't make post.

### ISSUE THREAD

**Issue by e80sam** [pinkynrg/convergence2.0#167]
I get the following error "Whoops, looks like something went wrong." when I make a post.  Happened a few times during my shift.

**Comment by e80sam** [comment]
Received the same error logging in.

**Comment by pinkynrg** [comment]
temporary solved. to much space occupied on server so the website couldn't execute properly. Now you should be able to use the website no problem. 

Need to create script to move backup on secondary machine.

**Comment by pinkynrg** [comment]
closing. creating a new issue.
