### ISSUE TITLE
Create script to download daily backups on E80 local server

### ISSUE THREAD

**Issue by pinkynrg** [pinkynrg/convergence2.0#169]
@EffEss can we have an E80 server that runs a script to download the daily backups from our Digital Ocean server? we have little hard disk on that and recently we filled it up and convergence obviously stopped working. 

Ideally a Linux machine would be better so I could just use a bash script with a rsync to do it. If it is not possibile we'll figure out how to do it with Windows.

**Comment by EffEss** [comment]
We can use the Ubuntu VM ...2.40 for this.

**Comment by pinkynrg** [comment]
can i have access to it? I would need ssh access and that's it pretty much

**Comment by pinkynrg** [comment]
The following command will be executed daily @ 3AM:

```
rsync -ae "ssh -p 1010" /home/forge/convergence.elettric80inc.com/backups repository@38.140.126.75:/media/SVN_REPO/Convergence
```

Before closing I'll check tomorrow if the syncing executed correctly.

**Comment by pinkynrg** [comment]
the script worked fine over night. Closing.
