### ISSUE TITLE
Text formatting problem with next lines

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#170]
I copied pasted some code from a note pad file such as the code below which looks with good formatting when I write the post but after submitting the post the next line breaks are gone and the code gets put together.

Original
  8:  SKIP CONDITION DI[107:Slow Robot Quote Limit]=ON    ;
   9:L PR[1] R[71:SLOW SPEED]mm/sec CNT0 Skip,LBL[3]    ;
  10:  LBL[3] ;
  11:   ;
  12:  SKIP CONDITION DI[108:Stop Robot Quote Limit]=ON    ;
  13:L PR[1] R[72:STOP SPEED]mm/sec FINE Skip,LBL[4]    ;
  14:  WAIT    .30(sec) ;

After submitting
  8:  SKIP CONDITION DI[107:Slow Robot Quote Limit]=ON    ;  9:L PR[1] R[71:SLOW SPEED]mm/sec CNT0 Skip,LBL[3]    ;  10:  LBL[3] ;  11:   ;  12:  SKIP CONDITION DI[108:Stop Robot Quote Limit]=ON    ;  13:L PR[1] R[72:STOP SPEED]mm/sec FINE Skip,LBL[4]    ;  14:  WAIT    .30(sec) ;

**Comment by pinkynrg** [comment]
please read how to write `inline code` and

```
block of code
that goes 
next
line
```

look for markdown on google.

**Comment by pinkynrg** [comment]
And please do not copy and paste: fix a little what you pasted. What you pasted has several spaces in front of every line of code you pasted. I will disable the paste otherwise of copies of more then 30 characters.

**Comment by pinkynrg** [comment]
this is how you can make it look like by fixing it a little: 

https://convergence.elettric80inc.com/posts/20355
