### ISSUE TITLE
Slack links

### ISSUE THREAD

**Issue by e80sam** [pinkynrg/convergence2.0#178]
Some links posted in slack by the convergence bot are set to local host.  screenshot of example message from 6/28/2016.
![2016-06-28 18_21_26](https://cloud.githubusercontent.com/assets/18336458/16435647/33cfe378-3d5d-11e6-8627-6d731e5c32da.png)

**Comment by e80sam** [comment]
clicking on 4616 sends you to http://localhost/tickets/4616

**Comment by e80tom** [comment]
There's already a ticket for this. :-)

**Comment by e80sam** [comment]
Ticket can be closed
