### ISSUE TITLE
Associate group id to contact created through company form 

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#182]
I created two new companies for sunopta and now when i click them i get a whoops error

![image](https://cloud.githubusercontent.com/assets/17487070/16672706/737327ee-446d-11e6-936a-8e1387c4f8f2.png)

**Comment by pinkynrg** [comment]
now the company is showing fine. I will need automatically associate the group id to the first contact created through the company form.

**Comment by pinkynrg** [comment]
fixed. closing
