### ISSUE TITLE
Photos Uploaded By Phone

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#25]
Don't Display as the other photos.

**Comment by pinkynrg** [comment]
what do you mean? what is different?

**Comment by pinkynrg** [comment]
@e80tom read above

**Comment by pinkynrg** [comment]
done.

**Comment by e80tom** [comment]
Photos posted in initial post do not open in picture viewer.  They are downloaded instead.  This is on the computer, not on the phone.
