### ISSUE TITLE
contact group permission type

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#52]
When creating a new company the main contact has the group permission type set to null "-" and the user has to choose customer. To avoid mistakes giving bad permissions this main contact should be defaulted to have the permission of a customer.

Similarly when you open an existing company and create a contact the group permission type is set to a default of "-". To avoid mistakes would we want to set to a default the permission as "customer" when the contact is made for a company that is not Elettric80. Although to avoid hardcoding that may require a new field for the company description to be set as internal so Elettric80 Inc company would be "internal".

**Comment by pinkynrg** [comment]
yes I did take care of this by creating 2 defaults groups "host". when add contact to e80 assign group "host" customer, when not e80, assign "host" employee, I still need to push the modification. 

I'll let you know when you can try this.

**Comment by pinkynrg** [comment]
this issue is solved.
