### ISSUE TITLE
After last import "TODO LIST"

### ISSUE THREAD

**Issue by pinkynrg** [pinkynrg/convergence2.0#54]
1) Add email emails contact to all contacts or remove them.
    `
    SELECT * FROM company_person WHERE email IS NULL
`
    http://local.convergence.it/contacts/[id]/edit
2) Get all WCF tickets and assign them a contact.
    `
    SELECT * FROM tickets WHERE contact_id IS NULL AND status_id = 3
`
    http://local.convergence.it/tickets/[id]/edit

**Comment by pinkynrg** [comment]
Remove E80 old company query:

```
DELETE FROM company_main_contacts WHERE company_id = 178; DELETE FROM company_person WHERE company_id = 178; DELETE FROM equipment WHERE company_id = 178; DELETE FROM posts WHERE ticket_id IN ( SELECT id FROM tickets WHERE company_id = 178 ); SET foreign_key_checks = 0; DELETE FROM tickets_history WHERE ticket_id IN ( SELECT id FROM tickets WHERE company_id = 178 ); SET foreign_key_checks = 1; DELETE FROM tickets WHERE company_id = 178; DELETE FROM companies WHERE id = 178;
```

**Comment by pinkynrg** [comment]
SET foreign_key_checks = 0;
DELETE FROM tickets_history;
SET foreign_key_checks = 1;
DELETE FROM posts;
DELETE FROM tag_ticket;
DELETE FROM ticket_links;
DELETE FROM tickets;
DELETE FROM company_main_contacts;
DELETE FROM company_account_managers;
UPDATE users SET active_contact_id = NULL WHERE 1=1;

**Comment by pinkynrg** [comment]
waiting feedback from Sam e Phan to update ticket contact on #4544 and #4018

**Comment by e80sam** [comment]
Updated contact for ticket 4544

**Comment by pinkynrg** [comment]
Also ticket 4018 was updated. Closing.
