### ISSUE TITLE
One row instead of two for half screen browser

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#61]
![2016-03-08 10_12_28](https://cloud.githubusercontent.com/assets/17487070/13607614/930fbe7a-e516-11e5-9802-28a92afe90a4.png)
![2016-03-08 10_12_56](https://cloud.githubusercontent.com/assets/17487070/13607613/92ddd3ba-e516-11e5-92ec-a3fcb786b3f5.png)

**Comment by pinkynrg** [comment]
that is not possibile since bootstrap grid is not elastic enough to allow it. Closing.
