### ISSUE TITLE
post time using draft time and not submit time

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#62]
while testing with both customer and employee account I noticed that one of the post from the customer shows the post time as the time when the draft was started. The post time is a few minutes later, the ticket history shows the correct post or modification time as the ticket also changed status but the list of post does not show the correct time.

![posttime](https://cloud.githubusercontent.com/assets/16998313/13610639/49859c6c-e524-11e5-83dd-4cd2fe4f6158.PNG)
![posttime2](https://cloud.githubusercontent.com/assets/16998313/13610640/4a6f5186-e524-11e5-8932-f29015e0c185.PNG)

**Comment by pinkynrg** [comment]
done. check @ next push.
