### ISSUE TITLE
Add button for the customer to be able to change a ticket to closed

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#67]
Add button for the customer to be able to change a ticket to closed, we can also close tickets but in this way the customer can close tickets by themselves avoid us to get an update to close and then close the ticket.

**Comment by pinkynrg** [comment]
I would like to keep thing as simple as possible on the user site. 

I am thinking automatically close the ticket after 1 month it's been solved or close it manually only when the current status is solved.
