### ISSUE TITLE
Hide the escalation deadline on the customer side and rename column in general

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#68]
Initially after launching the new site I believe it may be better to hide the "work" column on the customer side so that it gives our Help Desk team some time to adjust to the new tools and way of working. Then a couple of months later if we are caught up with our processes we can look into making this information public.

For the column name it may be more descriptive to change the name to "Next Deadline" or simply "Deadline"

**Comment by pinkynrg** [comment]
done.
