### ISSUE TITLE
"Connection Option" import incorrect

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#83]
![2016-03-24 14_33_58](https://cloud.githubusercontent.com/assets/17487070/14029014/9d524308-f1cd-11e5-9601-e1e81e6a2ee4.png)

**Comment by pinkynrg** [comment]
this is not an attribute of the ticket. It is an attribute of the company. I'll check if the other connection types have been imported correctly.

**Comment by pinkynrg** [comment]
test

**Comment by pinkynrg** [comment]
test2

**Comment by pinkynrg** [comment]
done
