### ISSUE TITLE
Contact Imported incorrectly?

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#88]
![image](https://cloud.githubusercontent.com/assets/17487070/14088471/5a170c9c-f4f5-11e5-8abb-f80684535c84.png)

We can correct it in CV1.  I suppose parentheses shouldn't be allowed

**Comment by pinkynrg** [comment]
Fixing this maybe once the system is already running. Maybe for now let's correct what we see on C1.0. But the rest we can take care later. Closing.
