### ISSUE TITLE
spell check in first ticket post

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#89]
![image](https://cloud.githubusercontent.com/assets/17487070/14088578/0bcd1f58-f4f6-11e5-9638-974cd40652e8.png)
![2016-03-28 15_01_43](https://cloud.githubusercontent.com/assets/17487070/14088583/14b05d06-f4f6-11e5-9c4d-d7c576ba9f7d.png)

It works in the title but not in the post.

**Comment by e80tom** [comment]
![image](https://cloud.githubusercontent.com/assets/17487070/14088735/bf125a7e-f4f6-11e5-9fa2-e70196dcc518.png)

Also in the other posts.

**Comment by pinkynrg** [comment]
replacing CKeditor with textile editor. Closing.
