### ISSUE TITLE
Linking tickets

### ISSUE THREAD

**Issue by e80sam** [pinkynrg/convergence2.0#95]
![2016-04-08 17_08_12](https://cloud.githubusercontent.com/assets/18336458/14398786/846de33e-fdac-11e5-9b62-9fd8c7490867.png)

No option to link additional tickets after ticket creation.

**Comment by pinkynrg** [comment]
the link can be added by editing the ticket. If you cannot edit a ticket it means you have not enough privileges. I'll give you more privileges.

**Comment by pinkynrg** [comment]
... so you can test!
